AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NBOX Infrastructure - Unified Template
  Uses GlobalTable resource for all envs to avoid code duplication.


Parameters:

  Prefix:
    Type: String
    Default: nbox
    Description: prefix for all resources name

  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
    Description: Environment name.


Conditions:
  IsProduction: !Equals [!Ref Environment, "production"]


Resources:


  EntriesTable:
    Type: AWS::DynamoDB::GlobalTable
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Properties:
      TableName: !Sub "${Prefix}-entries-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Path
          AttributeType: S
        - AttributeName: Key
          AttributeType: S
      KeySchema:
        - AttributeName: Path
          KeyType: HASH
        - AttributeName: Key
          KeyType: RANGE
      Replicas:
        - Region: us-east-1
          DeletionProtectionEnabled: !If [IsProduction, true, false]
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
          Tags:
            - Key: project
              Value: !Ref Prefix
            - Key: environment
              Value: !Ref Environment

  TrackingEntriesTable:
    Type: AWS::DynamoDB::GlobalTable
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Properties:
      TableName: !Sub "${Prefix}-tracking-entries-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Key
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: Key
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: TTL
      Replicas:
        - Region: us-east-1
          DeletionProtectionEnabled: !If [IsProduction, true, false]
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
          Tags:
            - Key: project
              Value: !Ref Prefix
            - Key: environment
              Value: !Ref Environment


  BoxTable:
    Type: AWS::DynamoDB::GlobalTable
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Properties:
      TableName: !Sub "${Prefix}-box-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Service
          AttributeType: S
        - AttributeName: Stage
          AttributeType: S
      KeySchema:
        - AttributeName: Service
          KeyType: HASH
        - AttributeName: Stage
          KeyType: RANGE
      Replicas:
        - Region: us-east-1
          DeletionProtectionEnabled: !If [IsProduction, true, false]
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
          Tags:
            - Key: project
              Value: !Ref Prefix
            - Key: environment
              Value: !Ref Environment


  PrefixConfigTable:
    Type: AWS::DynamoDB::GlobalTable
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Properties:
      TableName: !Sub "${Prefix}-prefix-config-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Prefix
          AttributeType: S
      KeySchema:
        - AttributeName: Prefix
          KeyType: HASH
      Replicas:
        - Region: us-east-1
          DeletionProtectionEnabled: !If [IsProduction, true, false]
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
          Tags:
            - Key: project
              Value: !Ref Prefix
            - Key: environment
              Value: !Ref Environment
            - Key: version
              Value: v2


  BoxBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: !Sub "${Prefix}-box-${Environment}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      Tags:
        - Key: project
          Value: !Ref Prefix
        - Key: environment
          Value: !Ref Environment

# =========================================================
# Outputs
# =========================================================
Outputs:
  EntriesTableName:
    Value: !Ref EntriesTable
  TrackingEntriesTableName:
    Value: !Ref TrackingEntriesTable
  BoxTableName:
    Value: !Ref BoxTable
  PrefixConfigTableName:
    Value: !Ref PrefixConfigTable
  BucketName:
    Value: !Ref BoxBucket