### token
POST {{baseUrl}}/api/auth/token
Content-Type: application/json


{
  "username": "user",
  "password": "pass"
}

> {%
    client.global.set("token", response.body.token);
%}


### create template
POST {{baseUrl}}/api/box
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "payload": {
    "service": "widget-x",
    "stage": {
      "development": {
        "template": {
          "name": "task_definition.json",
          "value": "ewogICAiRU5WXzEiOiAie3dpZGdldC14LmRldmVsb3BtZW50LmtleX0iLAogICAiRU5WXzIiOiAie3dpZGdldC14LmRldmVsb3BtZW50LmRlYnVnfSIsCiAgICJHTE9CQUxfU0VSVklDRSI6ICJ7d2lkZ2V0LXguc2VudHJ5fSIsCiAgICJkb21haW4iOiAie3ByaXZhdGUtZG9tYWlufSIsCiAgICJ2ZXJzaW9uIjogIjEiCn0K"
        }
      }
    }
  }
}


### get all boxes
GET {{baseUrl}}/api/box
Authorization: Bearer {{token}}
Content-Type: application/json



### check exist template
HEAD {{baseUrl}}/api/box/widget-x/development/task_definition.json
Authorization: Bearer {{token}}
Content-Type: application/json


### get template
GET {{baseUrl}}/api/box/example/development/task_definition.json
Authorization: Bearer {{token}}
Content-Type: application/json


### vars template
GET {{baseUrl}}/api/box/example/development/task_definition.json/vars
Authorization: Bearer {{token}}
Content-Type: application/json


### build template
GET {{baseUrl}}/api/box/crossborder-api/development/task_definition.json/build
Authorization: Bearer {{token}}
Content-Type: application/json


### create
POST {{baseUrl}}/api/entry
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {"key": "global/example/var001", "value": "var en dynamodb v5"},
  {"key": "global/example/var-ultra-secret", "value": "var en dynamodb v5", "secure": true},
  {"key": "global/example/var-ultra-secret2", "value": "var en dynamodb v5.1", "secure": true},
  {"key": "development/serverless/url-example", "value": "valor en parameter store v5"},
  {"key": "development/example/name", "value": "nbox v1"},
  {"key": "passbox/vault-1", "value": "pass ultra secret v5"}
]


### testing create
POST {{baseUrl}}/api/entry
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "key": "global/example/debug",
    "value": "active"
  },
  {
    "key": "global/example/new-secure-1",
    "value": "ooohh",
    "secure": true
  },
  {
    "key": "global/example/new-secure-2",
    "value": "ooohh",
    "secure": true
  },
  {
    "key": "global/example/unique-key7",
    "value": "secret-1234",
    "secure": true
  }
]


### Get key
GET {{baseUrl}}/api/entry/key?v=development/serverless/url-example
Authorization: Bearer {{token}}
Content-Type: application/json


### retrieve secret value
GET {{baseUrl}}/api/entry/resolve?v=passbox/vault-1
Authorization: Bearer {{token}}
Content-Type: application/json


### retrieve many keys
POST {{baseUrl}}/api/entry/lookup
Authorization: Bearer {{token}}
Content-Type: application/json

[
  "global/example/var001",
  "global/example/var-ultra-secret",
  "global/example/var-ultra-secret2",
  "development/serverless/url-example",
  "development/example/name",
  "passbox/vault-1"
]



### Get prefix
GET {{baseUrl}}/api/entry/prefix?v=passbox
Content-Type: application/json
Authorization: Bearer {{token}}


### list tracking history
GET {{baseUrl}}/api/track/key?v=passbox/vault-1&from=15m
Content-Type: application/json
Authorization: Bearer {{token}}



### all environments
GET {{baseUrl}}/api/static/environments
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete key
DELETE {{baseUrl}}/api/entry/key?v=widget-x/development3
Authorization: Bearer {{token}}
Content-Type: application/json



### Export entries
GET {{baseUrl}}/api/entry/export?prefix=global/example&format=ecs
Authorization: Bearer {{token}}
Content-Type: application/json



### List all Prefix config
GET {{baseUrl}}/api/prefix
Authorization: Bearer {{token}}
Content-Type: application/json



### Resolve Prefix config
GET {{baseUrl}}/api/prefix/resolve?v=development/serverless
Authorization: Bearer {{token}}
Content-Type: application/json



### Backends Prefix config
GET {{baseUrl}}/api/prefix/backends
Authorization: Bearer {{token}}
Content-Type: application/json
