package exporter

import (
	"bytes"
	"testing"

	"nbox/internal/entry"
)

// TestDotenvExport_CharacterizationOutput pins the exact byte output produced
// by Export so that a refactoring to bytes.Buffer can be confirmed identical.
func TestDotenvExport_CharacterizationOutput(t *testing.T) {
	e := NewDotenv()

	entries := []entry.Entry{
		{ShortKey: "api_key", Value: "simple"},
		{ShortKey: "db-host", Value: "localhost"},
		{ShortKey: "greeting", Value: "hello world"},
		{ShortKey: "token", Value: `it has "quotes"`},
		{ShortKey: "path", Value: `C:\some\path`},
		// empty ShortKey: Key is used instead
		{Key: "production/myapp/fallback", ShortKey: "", Value: "used_key"},
	}

	got, err := e.Export(entries)
	if err != nil {
		t.Fatalf("Export returned error: %v", err)
	}

	// Run Export a second time and confirm deterministic output.
	got2, err := e.Export(entries)
	if err != nil {
		t.Fatalf("Export (second call) returned error: %v", err)
	}
	if !bytes.Equal(got, got2) {
		t.Fatalf("Export is non-deterministic:\nfirst:  %q\nsecond: %q", got, got2)
	}

	// Pin the exact output bytes as a reference string. This value was
	// generated by running the test once against the original implementation.
	// If the output changes this test will fail, alerting us to a regression.
	//
	// To regenerate: delete the want constant, run the test with -v and note
	// the "got" output in the failure message, then paste it back.
	want := "API_KEY=simple\nDB_HOST=localhost\nGREETING=\"hello world\"\nTOKEN=\"it has \\\\\\\"quotes\\\\\\\"\"\nPATH=\"C:\\\\\\\\some\\\\\\\\path\"\nPRODUCTION_MYAPP_FALLBACK=used_key\n"
	if string(got) != want {
		t.Fatalf("Export output mismatch:\ngot:  %q\nwant: %q", string(got), want)
	}
}

// TestDotenvExport_Empty verifies that an empty slice produces an empty result.
func TestDotenvExport_Empty(t *testing.T) {
	e := NewDotenv()
	got, err := e.Export(nil)
	if err != nil {
		t.Fatalf("Export returned error: %v", err)
	}
	if len(got) != 0 {
		t.Fatalf("expected empty output, got %q", got)
	}
}
