// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Norlis Viamonte",
            "url": "http://www.example.com/support",
            "email": "norlis.viamonte@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/token": {
            "post": {
                "description": "authentication token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Token",
                "parameters": [
                    {
                        "description": "Payload",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.TokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token generated successfully",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                }
            }
        },
        "/api/box": {
            "get": {
                "description": "all templates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "List templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_box.Box"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "post": {
                "description": "insert or update templates on s3",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Upsert templates",
                "parameters": [
                    {
                        "description": "Upsert template",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_box.Command-internal_box_Box"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/box/schemas": {
            "get": {
                "description": "Get the list of supported storage backends",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "List Available Schema Types",
                "responses": {
                    "200": {
                        "description": "List of schema types (e.g. json, txt)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/box/{service}/{stage}": {
            "get": {
                "description": "show metadata \u0026 template names",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Stage detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "stage",
                        "name": "stage",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_box.Stage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/box/{service}/{stage}/{template}": {
            "get": {
                "description": "detail",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Retrieve template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "stage",
                        "name": "stage",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "template name",
                        "name": "template",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "post": {
                "description": "insert or update a specific template on s3",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Upsert template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "stage name",
                        "name": "stage",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "template name",
                        "name": "template",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Template content (Base64 encoded)",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_box.Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of updated paths",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "head": {
                "description": "Check the existence of the template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Exist template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "stage",
                        "name": "stage",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "template name",
                        "name": "template",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "exist": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/box/{service}/{stage}/{template}/build": {
            "get": {
                "description": "replace vars patterns",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Build template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "stage",
                        "name": "stage",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "template name",
                        "name": "template",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/box/{service}/{stage}/{template}/vars": {
            "get": {
                "description": "show all vars in template",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "List vars template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "stage",
                        "name": "stage",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "template name",
                        "name": "template",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/boxspec/reload": {
            "post": {
                "description": "Hot-reload specs from filesystem without restart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boxspec"
                ],
                "summary": "Reload validation specs",
                "responses": {
                    "200": {
                        "description": "count of loaded specs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/boxspec/resolve": {
            "get": {
                "description": "Given a filename pattern, resolves the matching spec and returns its JSON Schema representation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boxspec"
                ],
                "summary": "Resolve spec and export as JSON Schema",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filename pattern to match (e.g., task-definition.json)",
                        "name": "pattern",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON Schema",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing pattern parameter",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "404": {
                        "description": "No matching spec found",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/boxspec/specs": {
            "get": {
                "description": "Get list of schemas available for template validation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boxspec"
                ],
                "summary": "List available validation specs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/nbox_internal_box_store_spec.SpecDefinition"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/boxspec/validate": {
            "post": {
                "description": "Check if a template complies with defined specs without saving",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Validate template",
                "parameters": [
                    {
                        "description": "Template data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_box.ValidateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nbox_internal_box_store_spec.ValidationResult"
                        }
                    },
                    "400": {
                        "description": "Validation Failed",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                }
            }
        },
        "/api/entry": {
            "post": {
                "description": "insert / update vars",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Upsert entries",
                "parameters": [
                    {
                        "description": "Upsert template",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_entry.Entry"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/entry/export": {
            "get": {
                "description": "Export entries in different formats (JSON, YAML, dotenv, ECS task definition) for backup or migration purposes\nRequires authentication via Bearer token",
                "produces": [
                    "application/json",
                    "application/x-yaml",
                    "text/plain"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Export configuration entries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prefix to filter entries (required). Example: 'production/', 'staging/myapp/'",
                        "name": "prefix",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "json",
                            "yaml",
                            "dotenv",
                            "ecs"
                        ],
                        "type": "string",
                        "default": "json",
                        "description": "Output format",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exported file with entries",
                        "schema": {
                            "type": "file"
                        },
                        "headers": {
                            "Content-Disposition": {
                                "type": "string",
                                "description": "attachment; filename=nbox-export-{prefix}-{timestamp}.{ext}"
                            },
                            "X-Export-Count": {
                                "type": "string",
                                "description": "Number of entries exported"
                            },
                            "X-Export-Size": {
                                "type": "string",
                                "description": "Size in bytes of exported file"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid parameters (missing prefix or invalid format)",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "404": {
                        "description": "No entries found with specified prefix",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/entry/key": {
            "get": {
                "description": "detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Retrieve key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key path",
                        "name": "v",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_entry.Entry"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "delete keys \u0026 children",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key path",
                        "name": "v",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/entry/lookup": {
            "post": {
                "description": "Retrieve values and metadata for a list of keys in a single request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Retrieve multiple entries",
                "parameters": [
                    {
                        "description": "List of keys to retrieve",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/internal_entry.Entry"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/entry/prefix": {
            "get": {
                "description": "list all keys by path",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Filter by prefix",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key path",
                        "name": "v",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_entry.Entry"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/entry/resolve": {
            "get": {
                "description": "plain value",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Resolve value",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key path",
                        "name": "v",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_entry.Entry"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/me/permissions": {
            "get": {
                "description": "Returns the permission names and resource patterns granted to the authenticated caller's roles (UI hints, not a security boundary).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Current caller capabilities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/prefix": {
            "get": {
                "description": "Get the list of configurations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prefix-config"
                ],
                "summary": "List Available configs",
                "responses": {
                    "200": {
                        "description": "List of prefix config",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_prefix.Config"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/prefix/backends": {
            "get": {
                "description": "Get the list of supported storage backends",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prefix-config"
                ],
                "summary": "List Available Backend Types",
                "responses": {
                    "200": {
                        "description": "List of backend types (e.g. dynamodb, parameterstore)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/prefix/resolve": {
            "get": {
                "description": "plain value",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prefix-config"
                ],
                "summary": "Prefix config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "prefix path",
                        "name": "v",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_prefix.Config"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/static/stages": {
            "get": {
                "description": "Returns the list of available stages",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "static"
                ],
                "summary": "List available stages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/track/key": {
            "get": {
                "description": "history changes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracking"
                ],
                "summary": "History",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key path",
                        "name": "v",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time. Supports: 30m, 2h, 1.5d, 2w, 1M or ISO-8601",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time. Supports: 30m, 2h, 1.5d, 2w, 1M or ISO-8601",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_tracking.Record"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/problem.Detail"
                        }
                    }
                },
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ]
            }
        }
    },
    "definitions": {
        "internal_auth.TokenRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_box.Box": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "stage": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/internal_box.Stage"
                    }
                }
            }
        },
        "internal_box.Command-internal_box_Box": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "payload": {
                    "$ref": "#/definitions/internal_box.Box"
                }
            }
        },
        "internal_box.Input": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "internal_box.Stage": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/internal_box.TemplateMetadata"
                },
                "template": {
                    "$ref": "#/definitions/internal_box.Template"
                }
            }
        },
        "internal_box.Template": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "s3 path",
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_box.TemplateMetadata": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_box.ValidateInput": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            }
        },
        "internal_entry.Entry": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "development/service/var-example"
                },
                "metadata": {
                    "$ref": "#/definitions/internal_entry.Metadata"
                },
                "secure": {
                    "type": "boolean",
                    "example": false
                },
                "value": {
                    "type": "string",
                    "example": "value 123"
                }
            }
        },
        "internal_entry.Metadata": {
            "type": "object",
            "properties": {
                "fingerprint": {
                    "type": "string"
                },
                "storageBackend": {
                    "$ref": "#/definitions/nbox_internal_prefix.StorageBackendType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_prefix.Config": {
            "type": "object",
            "properties": {
                "prefix": {
                    "description": "PK",
                    "type": "string"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "typeAllowed": {
                    "description": "TODO: Deprecated",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_prefix.StorageBackendType"
                    }
                },
                "typeDefault": {
                    "$ref": "#/definitions/internal_prefix.StorageBackendType"
                },
                "typeSecure": {
                    "$ref": "#/definitions/internal_prefix.StorageBackendType"
                }
            }
        },
        "internal_prefix.StorageBackendType": {
            "type": "string",
            "enum": [
                "dynamodb",
                "parameterstore",
                "parameterstore_secure"
            ],
            "x-enum-varnames": [
                "BackendDynamoDB",
                "BackendParameterStore",
                "BackendParameterStoreSecure"
            ]
        },
        "internal_tracking.Record": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "secure": {
                    "type": "boolean"
                },
                "storageBackend": {
                    "$ref": "#/definitions/nbox_internal_prefix.StorageBackendType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "nbox_internal_box_store_spec.SpecDefinition": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique identifier (e.g., \"aws:ecs:task-def-v1\")",
                    "type": "string"
                },
                "matchPatterns": {
                    "description": "Glob patterns (e.g., \"taskdef*.json\")",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "Human-readable name",
                    "type": "string"
                },
                "version": {
                    "description": "Schema version",
                    "type": "string"
                }
            }
        },
        "nbox_internal_box_store_spec.ValidationError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "path": {
                    "description": "e.g., \"containerDefinitions.0.memory\"",
                    "type": "string"
                }
            }
        },
        "nbox_internal_box_store_spec.ValidationResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nbox_internal_box_store_spec.ValidationError"
                    }
                },
                "spec": {
                    "$ref": "#/definitions/nbox_internal_box_store_spec.SpecDefinition"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "nbox_internal_prefix.StorageBackendType": {
            "type": "string",
            "enum": [
                "dynamodb",
                "parameterstore",
                "parameterstore_secure"
            ],
            "x-enum-varnames": [
                "BackendDynamoDB",
                "BackendParameterStore",
                "BackendParameterStoreSecure"
            ]
        },
        "problem.Detail": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Detail is a human-readable explanation specific to this occurrence.",
                    "type": "string"
                },
                "instance": {
                    "description": "Instance is a URI identifying the specific occurrence of the problem.",
                    "type": "string"
                },
                "requestId": {
                    "description": "RequestID correlates the problem to a specific request.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the HTTP status code for this occurrence.",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "Timestamp records when the problem was created.",
                    "type": "string"
                },
                "title": {
                    "description": "Title is a short, human-readable summary of the problem type.\nShould not change across occurrences of the same problem.",
                    "type": "string"
                },
                "type": {
                    "description": "Type is a URI identifying the problem type. Should provide\ndeveloper-readable documentation.",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "Bearer token authentication. Enter your JWT token in the format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "nbox API",
	Description:      "Esta es una API generada automáticamente con Swaggo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
